### ISSUE TITLE
Repository name is ambiguous, likely to conflict

### ISSUE THREAD

**Issue by DuncanCorps** [polestarglobal/ps-angular-typescript-components#1]
Here's the thing... I've often wanted to create a single repository with reusable Java/Spring components to eliminate the copying-and-pasting I've done recently. An obvious (and poor) name for that would be **ps-components**; you can see the problem.

It would be best to rename this repository to **ps-web-components** (given the text in _README.md_) or **ps-angular-typescript-components** (given the description - but maybe too specific, it would preclude other types of web component).

**Comment by vsrc** [comment]
👍  fair point, project name changed but should stay like this from now on.
